services:
  mono_bdd:
    container_name: mono_bdd
    image: mariadb:latest
    volumes:
    - ./mysql:/var/lib/mysql
    ports:
    - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: toor
      MARIADB_DATABASE: bddname
      MARIADB_USER: roger
      MARIADB_PASSWORD: regor

  mono_adminer:
    container_name: mono_adminer
    image: adminer
    ports:
    - 8080:8080
